apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod

spec:
  containers: 
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"] # command overrides the ENTRYPOINT field for the docker image.
      args: ["10"]  # overrides the CMD instructions in the docker file.
