apiVersion: v1
kind: Service
metadata:
  name: storage-backend-service
spec:
  selector:
    tags: backend-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
  type: NodePort
